### ISSUE TITLE
Does the app work for non-microsoft users?

### ISSUE THREAD

**Issue by whihathac** [microsoft/AzureKeyVaultExplorer#50]
I used to use this while working at MS. Now I can't seem to make it work with my new user ID/Azure subs.
Not sure if this is supported or the app needs to be updated to support TLS 1.2

![image](https://user-images.githubusercontent.com/7718462/177982855-79cde981-2091-42db-867c-d1daa5542d5d.png)

**Comment by jmorenab** [comment]
Hi, you can add this registry keys:
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319]"SchUseStrongCrypto"=dword:00000001
[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v4.0.30319]"SchUseStrongCrypto"=dword:00000001

**Comment by PhilippCh** [comment]
Would this also work for someone using .NET 6? In that case, I should probably change the version in the Registry path, right?

**Comment by JBoman32768** [comment]
Put this in a .REG file and merge it: (Famous last words)

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319]
"SchUseStrongCrypto"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v4.0.30319]
"SchUseStrongCrypto"=dword:00000001 
```

**Comment by whihathac** [comment]
Thanks it worked! (Forgot to reply!)

**Comment by ikshitijarora** [comment]
Hi, I have updated the keys in Registry but am still facing the same issue. Any help?
<img width="919" alt="image" src="https://github.com/microsoft/AzureKeyVaultExplorer/assets/140070330/f15e8b12-a86d-4c5a-9766-39edafdf9d6e">
<img width="918" alt="image" src="https://github.com/microsoft/AzureKeyVaultExplorer/assets/140070330/3afb608a-0e07-4043-bd66-9704deced1d8">
